### ISSUE TITLE
gql implementation concern

### ISSUE THREAD

**Issue by sphsmith** [hivdb/sierra-client#1]
Hello - liking the client, but the current implementation of the -q flag doesn't fully replicate gql since the code is hard-wired to extract only from sequenceAnalysis downward.  So for instance even though in gql I can request currentVersion easily enough, there is no way to do this through the sierra client.  Would you consider please allowing broader gql use if this is the direction of future development?  My only work around is to run `sierrapy -v` and cram the result into the json output manually.

**Comment by philiptzou** [comment]
Hi @sphsmith:

The version object can also be retrieved as a field of `drugResistance`, it is already [added to the default gql files](https://github.com/hivdb/sierra-client/blob/master/python/sierrapy/fragments/sequence_analysis_default.gql#L32) on Github. At current stage since we haven't release 0.1.2, you can download the new gql file and specify -q flag to it. After we released 0.1.2, it will be shipped in default queries.

**Comment by philiptzou** [comment]
Close this issue since we just released 0.1.2.
